### ISSUE TITLE
CI improvement

### ISSUE THREAD

**Issue by white-gecko** [RDFLib/rdflib#1248]
#1247 bought us a good step further.

We should still keep the following on our todo list:

- [x] New CI, No Travis anymore (-> #1247)
- [ ] Architectures: Do we want to test on ppc64le as well? Maybe we just drop it. Would it be possible to test other archs like armhf and arm64 in an emulator with drone?
- [ ] Branches: Do we nee to configure something for the release branches and prs or is this default already?
- [ ] Coveralls: Report coverage somwhere
- [ ] IRC: Report builds to irc or maybe matrix. Maybe we only need this if something is failing on master.

From .travis.yml
```
…
arch:
 - amd64
 - ppc64le
…
branches:
  only:
    # only build master and release branches (merge request are built anyhow)
    - master
    - /^\d+\.\d+\.\d+(-.*)?$/
…
after_success:
    - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi

notifications:
    irc:
        channels: "chat.freenode.net#rdflib"
```
